import java.io.IOException;
import java.util.concurrent.TimeoutException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException, TimeoutException {
    	
    }
    
}
